# Generated by Django 4.1.2 on 2022-10-30 12:33

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(default=None, max_length=50)),
                ('Blog_Description', tinymce.models.HTMLField()),
                ('Blog_Image', models.ImageField(upload_to='Blogs')),
                ('Blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Blog_Title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slider_Image', models.ImageField(default=None, upload_to='slider/')),
            ],
        ),
    ]
