# Generated by Django 4.1.2 on 2022-12-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slider_Blogs_and_others', '0003_siteuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Siteuser',
        ),
    ]
