# Generated by Django 4.1.2 on 2022-12-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slider_Blogs_and_others', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Phone_Number',
            field=models.IntegerField(default=None),
        ),
    ]
