# Generated by Django 4.1.2 on 2022-12-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slider_Blogs_and_others', '0009_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hited_user', models.TextField(default=None)),
            ],
        ),
    ]
