# Generated by Django 4.1.2 on 2022-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slider_Blogs_and_others', '0010_count_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count_user',
            name='hited_user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
