# Generated by Django 4.1.2 on 2022-12-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slider_Blogs_and_others', '0011_alter_count_user_hited_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Count_User',
            new_name='Visitors',
        ),
        migrations.RenameField(
            model_name='visitors',
            old_name='hited_user',
            new_name='Visitors',
        ),
    ]
