# Generated by Django 4.1.2 on 2022-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0004_alter_product_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Product_Name', models.CharField(default=None, max_length=30)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
