# Generated by Django 4.1.2 on 2022-11-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0005_add_to_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_to_cart',
            new_name='Cart',
        ),
    ]
