# Generated by Django 4.1.2 on 2022-11-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0007_remove_cart_product_name_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
