# Generated by Django 4.1.2 on 2022-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0009_alter_cart_product_id_alter_cart_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product_ID',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
