# Generated by Django 4.1.2 on 2022-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0013_rename_customer_placed_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_order',
            name='Address',
            field=models.CharField(max_length=20),
        ),
    ]
