# Generated by Django 4.1.2 on 2022-12-08 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Slider_Blogs_and_others', '0008_alter_customer_phone_number'),
        ('productmanagement', '0014_alter_placed_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_order',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slider_Blogs_and_others.customer'),
        ),
    ]
