# Generated by Django 4.1.2 on 2022-12-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0015_alter_placed_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placed_order',
            name='Address',
        ),
        migrations.AddField(
            model_name='placed_order',
            name='City',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='Full_Address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='Phone_Number',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='placed_order',
            name='Zipcode',
            field=models.IntegerField(default=None),
        ),
    ]
