# Generated by Django 4.1.2 on 2022-12-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0016_remove_placed_order_address_placed_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.IntegerField(default=None),
        ),
    ]
