# Generated by Django 4.1.2 on 2022-12-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0018_remove_cart_product_cart_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product_Id',
            new_name='Product',
        ),
    ]
