# Generated by Django 4.1.2 on 2022-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0019_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed_order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
